// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: logs.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LEVEL_INFO        LogLevel = 2
	LogLevel_LEVEL_WARN        LogLevel = 3
	LogLevel_LEVEL_ERROR       LogLevel = 4
	LogLevel_LEVEL_FATAL       LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
		5: "LEVEL_FATAL",
	}
	LogLevel_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
		"LEVEL_FATAL":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logs_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_logs_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

// LogsPayload: batch of logs from agent
type LogsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Logs          []*LogRecord           `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsPayload) Reset() {
	*x = LogsPayload{}
	mi := &file_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsPayload) ProtoMessage() {}

func (x *LogsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsPayload.ProtoReflect.Descriptor instead.
func (*LogsPayload) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogsPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogsPayload) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LogsPayload) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogsPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// LogRecord: single log entry
type LogRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Level       LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=pulse.v1.LogLevel" json:"level,omitempty"`
	Message     string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Optional trace context (link to spans)
	TraceId    string            `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId     string            `protobuf:"bytes,5,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Attributes map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // structured fields
	// Stack trace for errors
	StackTrace    string `protobuf:"bytes,7,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	ServiceName   string `protobuf:"bytes,8,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	LoggerName    string `protobuf:"bytes,9,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogRecord) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogRecord) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_UNSPECIFIED
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogRecord) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *LogRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRecord) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

// LogsQuery: search historical logs
type LogsQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // full-text search
	StartTimeMs   int64                  `protobuf:"varint,3,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,4,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	Levels        []LogLevel             `protobuf:"varint,5,rep,packed,name=levels,proto3,enum=pulse.v1.LogLevel" json:"levels,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder     string                 `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc", "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsQueryRequest) Reset() {
	*x = LogsQueryRequest{}
	mi := &file_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsQueryRequest) ProtoMessage() {}

func (x *LogsQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsQueryRequest.ProtoReflect.Descriptor instead.
func (*LogsQueryRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogsQueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogsQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LogsQueryRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *LogsQueryRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *LogsQueryRequest) GetLevels() []LogLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *LogsQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LogsQueryRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// LogsQueryResponse: matching logs
type LogsQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogRecord           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	QueryTimeMs   int64                  `protobuf:"varint,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	TotalMatches  int64                  `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsQueryResponse) Reset() {
	*x = LogsQueryResponse{}
	mi := &file_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsQueryResponse) ProtoMessage() {}

func (x *LogsQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsQueryResponse.ProtoReflect.Descriptor instead.
func (*LogsQueryResponse) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogsQueryResponse) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogsQueryResponse) GetQueryTimeMs() int64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

func (x *LogsQueryResponse) GetTotalMatches() int64 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

// LogPattern: detected repeated log pattern
type LogPattern struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pattern          string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Count            int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ExampleMessage   string                 `protobuf:"bytes,3,opt,name=example_message,json=exampleMessage,proto3" json:"example_message,omitempty"`
	AffectedServices []string               `protobuf:"bytes,4,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	ErrorCorrelation float64                `protobuf:"fixed64,5,opt,name=error_correlation,json=errorCorrelation,proto3" json:"error_correlation,omitempty"` // correlation with errors
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogPattern) Reset() {
	*x = LogPattern{}
	mi := &file_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPattern) ProtoMessage() {}

func (x *LogPattern) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPattern.ProtoReflect.Descriptor instead.
func (*LogPattern) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{4}
}

func (x *LogPattern) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *LogPattern) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LogPattern) GetExampleMessage() string {
	if x != nil {
		return x.ExampleMessage
	}
	return ""
}

func (x *LogPattern) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *LogPattern) GetErrorCorrelation() float64 {
	if x != nil {
		return x.ErrorCorrelation
	}
	return 0
}

// LogAnomalies: anomaly detection result
type LogAnomalies struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Patterns        []*LogPattern          `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	DetectionTimeMs int64                  `protobuf:"varint,2,opt,name=detection_time_ms,json=detectionTimeMs,proto3" json:"detection_time_ms,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogAnomalies) Reset() {
	*x = LogAnomalies{}
	mi := &file_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAnomalies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAnomalies) ProtoMessage() {}

func (x *LogAnomalies) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAnomalies.ProtoReflect.Descriptor instead.
func (*LogAnomalies) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{5}
}

func (x *LogAnomalies) GetPatterns() []*LogPattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *LogAnomalies) GetDetectionTimeMs() int64 {
	if x != nil {
		return x.DetectionTimeMs
	}
	return 0
}

func (x *LogAnomalies) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetTraceLogsRequest: bir trace'e ait tum loglar.
// Loglari trace'e baglamak, uc ayagi (metrik/trace/log) birlestiren sey.
type GetTraceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceLogsRequest) Reset() {
	*x = GetTraceLogsRequest{}
	mi := &file_logs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceLogsRequest) ProtoMessage() {}

func (x *GetTraceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTraceLogsRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{6}
}

func (x *GetTraceLogsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetTraceLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListLogServicesRequest: hangi servisler log gonderiyor?
type ListLogServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogServicesRequest) Reset() {
	*x = ListLogServicesRequest{}
	mi := &file_logs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogServicesRequest) ProtoMessage() {}

func (x *ListLogServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogServicesRequest.ProtoReflect.Descriptor instead.
func (*ListLogServicesRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{7}
}

type ListLogServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogServicesResponse) Reset() {
	*x = ListLogServicesResponse{}
	mi := &file_logs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogServicesResponse) ProtoMessage() {}

func (x *ListLogServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogServicesResponse.ProtoReflect.Descriptor instead.
func (*ListLogServicesResponse) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{8}
}

func (x *ListLogServicesResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// DetectPatternsRequest: tekrar eden log kaliplarini bul
type DetectPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	StartTimeMs   int64                  `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectPatternsRequest) Reset() {
	*x = DetectPatternsRequest{}
	mi := &file_logs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectPatternsRequest) ProtoMessage() {}

func (x *DetectPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectPatternsRequest.ProtoReflect.Descriptor instead.
func (*DetectPatternsRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{9}
}

func (x *DetectPatternsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DetectPatternsRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *DetectPatternsRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *DetectPatternsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_logs_proto protoreflect.FileDescriptor

const file_logs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"logs.proto\x12\bpulse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\vLogsPayload\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x04logs\x18\x03 \x03(\v2\x13.pulse.v1.LogRecordR\x04logs\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8f\x03\n" +
	"\tLogRecord\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12(\n" +
	"\x05level\x18\x02 \x01(\x0e2\x12.pulse.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x05 \x01(\tR\x06spanId\x12C\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2#.pulse.v1.LogRecord.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\vstack_trace\x18\a \x01(\tR\n" +
	"stackTrace\x12!\n" +
	"\fservice_name\x18\b \x01(\tR\vserviceName\x12\x1f\n" +
	"\vlogger_name\x18\t \x01(\tR\n" +
	"loggerName\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x10LogsQueryRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\"\n" +
	"\rstart_time_ms\x18\x03 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x04 \x01(\x03R\tendTimeMs\x12*\n" +
	"\x06levels\x18\x05 \x03(\x0e2\x12.pulse.v1.LogLevelR\x06levels\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\tR\tsortOrder\"\x85\x01\n" +
	"\x11LogsQueryResponse\x12'\n" +
	"\x04logs\x18\x01 \x03(\v2\x13.pulse.v1.LogRecordR\x04logs\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x03R\vqueryTimeMs\x12#\n" +
	"\rtotal_matches\x18\x03 \x01(\x03R\ftotalMatches\"\xbf\x01\n" +
	"\n" +
	"LogPattern\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12'\n" +
	"\x0fexample_message\x18\x03 \x01(\tR\x0eexampleMessage\x12+\n" +
	"\x11affected_services\x18\x04 \x03(\tR\x10affectedServices\x12+\n" +
	"\x11error_correlation\x18\x05 \x01(\x01R\x10errorCorrelation\"\x8e\x01\n" +
	"\fLogAnomalies\x120\n" +
	"\bpatterns\x18\x01 \x03(\v2\x14.pulse.v1.LogPatternR\bpatterns\x12*\n" +
	"\x11detection_time_ms\x18\x02 \x01(\x03R\x0fdetectionTimeMs\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"F\n" +
	"\x13GetTraceLogsRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x18\n" +
	"\x16ListLogServicesRequest\"5\n" +
	"\x17ListLogServicesResponse\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"\x94\x01\n" +
	"\x15DetectPatternsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\"\n" +
	"\rstart_time_ms\x18\x02 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x03 \x01(\x03R\tendTimeMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit*t\n" +
	"\bLogLevel\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x03\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x04\x12\x0f\n" +
	"\vLEVEL_FATAL\x10\x052\xc1\x02\n" +
	"\n" +
	"LogService\x12D\n" +
	"\tQueryLogs\x12\x1a.pulse.v1.LogsQueryRequest\x1a\x1b.pulse.v1.LogsQueryResponse\x12J\n" +
	"\fGetTraceLogs\x12\x1d.pulse.v1.GetTraceLogsRequest\x1a\x1b.pulse.v1.LogsQueryResponse\x12V\n" +
	"\x0fListLogServices\x12 .pulse.v1.ListLogServicesRequest\x1a!.pulse.v1.ListLogServicesResponse\x12I\n" +
	"\x0eDetectPatterns\x12\x1f.pulse.v1.DetectPatternsRequest\x1a\x16.pulse.v1.LogAnomaliesB,Z*github.com/nisah/pulse-metrics/pkg/pulsepbb\x06proto3"

var (
	file_logs_proto_rawDescOnce sync.Once
	file_logs_proto_rawDescData []byte
)

func file_logs_proto_rawDescGZIP() []byte {
	file_logs_proto_rawDescOnce.Do(func() {
		file_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)))
	})
	return file_logs_proto_rawDescData
}

var file_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_logs_proto_goTypes = []any{
	(LogLevel)(0),                   // 0: pulse.v1.LogLevel
	(*LogsPayload)(nil),             // 1: pulse.v1.LogsPayload
	(*LogRecord)(nil),               // 2: pulse.v1.LogRecord
	(*LogsQueryRequest)(nil),        // 3: pulse.v1.LogsQueryRequest
	(*LogsQueryResponse)(nil),       // 4: pulse.v1.LogsQueryResponse
	(*LogPattern)(nil),              // 5: pulse.v1.LogPattern
	(*LogAnomalies)(nil),            // 6: pulse.v1.LogAnomalies
	(*GetTraceLogsRequest)(nil),     // 7: pulse.v1.GetTraceLogsRequest
	(*ListLogServicesRequest)(nil),  // 8: pulse.v1.ListLogServicesRequest
	(*ListLogServicesResponse)(nil), // 9: pulse.v1.ListLogServicesResponse
	(*DetectPatternsRequest)(nil),   // 10: pulse.v1.DetectPatternsRequest
	nil,                             // 11: pulse.v1.LogRecord.AttributesEntry
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_logs_proto_depIdxs = []int32{
	2,  // 0: pulse.v1.LogsPayload.logs:type_name -> pulse.v1.LogRecord
	12, // 1: pulse.v1.LogsPayload.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: pulse.v1.LogRecord.level:type_name -> pulse.v1.LogLevel
	11, // 3: pulse.v1.LogRecord.attributes:type_name -> pulse.v1.LogRecord.AttributesEntry
	0,  // 4: pulse.v1.LogsQueryRequest.levels:type_name -> pulse.v1.LogLevel
	2,  // 5: pulse.v1.LogsQueryResponse.logs:type_name -> pulse.v1.LogRecord
	5,  // 6: pulse.v1.LogAnomalies.patterns:type_name -> pulse.v1.LogPattern
	3,  // 7: pulse.v1.LogService.QueryLogs:input_type -> pulse.v1.LogsQueryRequest
	7,  // 8: pulse.v1.LogService.GetTraceLogs:input_type -> pulse.v1.GetTraceLogsRequest
	8,  // 9: pulse.v1.LogService.ListLogServices:input_type -> pulse.v1.ListLogServicesRequest
	10, // 10: pulse.v1.LogService.DetectPatterns:input_type -> pulse.v1.DetectPatternsRequest
	4,  // 11: pulse.v1.LogService.QueryLogs:output_type -> pulse.v1.LogsQueryResponse
	4,  // 12: pulse.v1.LogService.GetTraceLogs:output_type -> pulse.v1.LogsQueryResponse
	9,  // 13: pulse.v1.LogService.ListLogServices:output_type -> pulse.v1.ListLogServicesResponse
	6,  // 14: pulse.v1.LogService.DetectPatterns:output_type -> pulse.v1.LogAnomalies
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_logs_proto_init() }
func file_logs_proto_init() {
	if File_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_proto_goTypes,
		DependencyIndexes: file_logs_proto_depIdxs,
		EnumInfos:         file_logs_proto_enumTypes,
		MessageInfos:      file_logs_proto_msgTypes,
	}.Build()
	File_logs_proto = out.File
	file_logs_proto_goTypes = nil
	file_logs_proto_depIdxs = nil
}
