// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: logs.proto

package pulsepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_QueryLogs_FullMethodName       = "/pulse.v1.LogService/QueryLogs"
	LogService_GetTraceLogs_FullMethodName    = "/pulse.v1.LogService/GetTraceLogs"
	LogService_ListLogServices_FullMethodName = "/pulse.v1.LogService/ListLogServices"
	LogService_DetectPatterns_FullMethodName  = "/pulse.v1.LogService/DetectPatterns"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// QueryLogs: servis, seviye, metin ve zaman araligiyla arama
	QueryLogs(ctx context.Context, in *LogsQueryRequest, opts ...grpc.CallOption) (*LogsQueryResponse, error)
	// GetTraceLogs: bir trace boyunca uretilen tum loglar
	GetTraceLogs(ctx context.Context, in *GetTraceLogsRequest, opts ...grpc.CallOption) (*LogsQueryResponse, error)
	// ListLogServices: arama formunu doldurmak icin
	ListLogServices(ctx context.Context, in *ListLogServicesRequest, opts ...grpc.CallOption) (*ListLogServicesResponse, error)
	// DetectPatterns: degiskenleri maskeleyip tekrar eden kaliplari sayar
	DetectPatterns(ctx context.Context, in *DetectPatternsRequest, opts ...grpc.CallOption) (*LogAnomalies, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) QueryLogs(ctx context.Context, in *LogsQueryRequest, opts ...grpc.CallOption) (*LogsQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsQueryResponse)
	err := c.cc.Invoke(ctx, LogService_QueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetTraceLogs(ctx context.Context, in *GetTraceLogsRequest, opts ...grpc.CallOption) (*LogsQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsQueryResponse)
	err := c.cc.Invoke(ctx, LogService_GetTraceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ListLogServices(ctx context.Context, in *ListLogServicesRequest, opts ...grpc.CallOption) (*ListLogServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLogServicesResponse)
	err := c.cc.Invoke(ctx, LogService_ListLogServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) DetectPatterns(ctx context.Context, in *DetectPatternsRequest, opts ...grpc.CallOption) (*LogAnomalies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAnomalies)
	err := c.cc.Invoke(ctx, LogService_DetectPatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
type LogServiceServer interface {
	// QueryLogs: servis, seviye, metin ve zaman araligiyla arama
	QueryLogs(context.Context, *LogsQueryRequest) (*LogsQueryResponse, error)
	// GetTraceLogs: bir trace boyunca uretilen tum loglar
	GetTraceLogs(context.Context, *GetTraceLogsRequest) (*LogsQueryResponse, error)
	// ListLogServices: arama formunu doldurmak icin
	ListLogServices(context.Context, *ListLogServicesRequest) (*ListLogServicesResponse, error)
	// DetectPatterns: degiskenleri maskeleyip tekrar eden kaliplari sayar
	DetectPatterns(context.Context, *DetectPatternsRequest) (*LogAnomalies, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) QueryLogs(context.Context, *LogsQueryRequest) (*LogsQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLogs not implemented")
}
func (UnimplementedLogServiceServer) GetTraceLogs(context.Context, *GetTraceLogsRequest) (*LogsQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceLogs not implemented")
}
func (UnimplementedLogServiceServer) ListLogServices(context.Context, *ListLogServicesRequest) (*ListLogServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLogServices not implemented")
}
func (UnimplementedLogServiceServer) DetectPatterns(context.Context, *DetectPatternsRequest) (*LogAnomalies, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectPatterns not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_QueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).QueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_QueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).QueryLogs(ctx, req.(*LogsQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetTraceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetTraceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetTraceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetTraceLogs(ctx, req.(*GetTraceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ListLogServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ListLogServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_ListLogServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ListLogServices(ctx, req.(*ListLogServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_DetectPatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectPatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DetectPatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_DetectPatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DetectPatterns(ctx, req.(*DetectPatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulse.v1.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryLogs",
			Handler:    _LogService_QueryLogs_Handler,
		},
		{
			MethodName: "GetTraceLogs",
			Handler:    _LogService_GetTraceLogs_Handler,
		},
		{
			MethodName: "ListLogServices",
			Handler:    _LogService_ListLogServices_Handler,
		},
		{
			MethodName: "DetectPatterns",
			Handler:    _LogService_DetectPatterns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
