// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: metrics.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType: gauge, counter, histogram, summary
type MetricType int32

const (
	MetricType_GAUGE     MetricType = 0
	MetricType_COUNTER   MetricType = 1
	MetricType_HISTOGRAM MetricType = 2
	MetricType_SUMMARY   MetricType = 3
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
		2: "HISTOGRAM",
		3: "SUMMARY",
	}
	MetricType_value = map[string]int32{
		"GAUGE":     0,
		"COUNTER":   1,
		"HISTOGRAM": 2,
		"SUMMARY":   3,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type AlertSeverity int32

const (
	AlertSeverity_INFO     AlertSeverity = 0
	AlertSeverity_WARNING  AlertSeverity = 1
	AlertSeverity_CRITICAL AlertSeverity = 2
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"CRITICAL": 2,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[1].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[1]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

// MetricsPayload: batch of metrics from agent
type MetricsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsPayload) Reset() {
	*x = MetricsPayload{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload) ProtoMessage() {}

func (x *MetricsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload.ProtoReflect.Descriptor instead.
func (*MetricsPayload) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricsPayload) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MetricsPayload) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Metric: single metric data point
type Metric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=pulse.v1.MetricType" json:"type,omitempty"`
	Value           float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Tags            map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels          map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampMillis int64                  `protobuf:"varint,6,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_GAUGE
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

// HistogramBucket: for histogram distributions
type HistogramBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Le            float64                `protobuf:"fixed64,1,opt,name=le,proto3" json:"le,omitempty"` // less-than-equal boundary
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket) Reset() {
	*x = HistogramBucket{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket) ProtoMessage() {}

func (x *HistogramBucket) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket.ProtoReflect.Descriptor instead.
func (*HistogramBucket) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *HistogramBucket) GetLe() float64 {
	if x != nil {
		return x.Le
	}
	return 0
}

func (x *HistogramBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SummaryValue: for quantile summaries
type SummaryValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantile      float64                `protobuf:"fixed64,1,opt,name=quantile,proto3" json:"quantile,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryValue) Reset() {
	*x = SummaryValue{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryValue) ProtoMessage() {}

func (x *SummaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryValue.ProtoReflect.Descriptor instead.
func (*SummaryValue) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryValue) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

func (x *SummaryValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// MetricsQuery: query request for historical metrics
type MetricsQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartTimeMs   int64                  `protobuf:"varint,4,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,5,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Aggregation   string                 `protobuf:"bytes,7,opt,name=aggregation,proto3" json:"aggregation,omitempty"`                 // "avg", "sum", "max", "min", "p50", "p95", "p99"
	InstanceId    string                 `protobuf:"bytes,8,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // bos ise tum instance'lar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryRequest) Reset() {
	*x = MetricsQueryRequest{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryRequest) ProtoMessage() {}

func (x *MetricsQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryRequest.ProtoReflect.Descriptor instead.
func (*MetricsQueryRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsQueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricsQueryRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricsQueryRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *MetricsQueryRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *MetricsQueryRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *MetricsQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MetricsQueryRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *MetricsQueryRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// MetricsQueryResponse: aggregated historical metrics
type MetricsQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*TimeSeriesData      `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	QueryTimeMs   int64                  `protobuf:"varint,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse) Reset() {
	*x = MetricsQueryResponse{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse) ProtoMessage() {}

func (x *MetricsQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsQueryResponse) GetSeries() []*TimeSeriesData {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *MetricsQueryResponse) GetQueryTimeMs() int64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

// TimeSeriesData: time-indexed metric values
type TimeSeriesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Type          MetricType             `protobuf:"varint,5,opt,name=type,proto3,enum=pulse.v1.MetricType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesData) Reset() {
	*x = TimeSeriesData{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesData) ProtoMessage() {}

func (x *TimeSeriesData) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesData.ProtoReflect.Descriptor instead.
func (*TimeSeriesData) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *TimeSeriesData) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *TimeSeriesData) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TimeSeriesData) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *TimeSeriesData) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TimeSeriesData) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_GAUGE
}

// DataPoint: single timestamp + value
type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *DataPoint) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// AlertRule: define alerting conditions
type AlertRule struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RuleId      string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	ServiceName string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MetricName  string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// condition: "<toplama> <operator> <sayi>"
	//
	//	toplama : avg | sum | min | max | last | p50 | p95 | p99 | zscore
	//	operator: > | >= | < | <=
	//
	// Ornek: "p95 > 500", "zscore > 3"
	// zscore istatistiksel anomali tespitidir: son deger, daha uzun bir
	// gecmisin ortalamasindan kac standart sapma uzakta?
	Condition       string        `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	DurationSeconds int32         `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // degerlendirme penceresi
	WebhookUrl      string        `protobuf:"bytes,6,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	Enabled         bool          `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAtMs     int64         `protobuf:"varint,8,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	Severity        AlertSeverity `protobuf:"varint,9,opt,name=severity,proto3,enum=pulse.v1.AlertSeverity" json:"severity,omitempty"`
	Name            string        `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *AlertRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AlertRule) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AlertRule) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *AlertRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AlertRule) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *AlertRule) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRule) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *AlertRule) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_INFO
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Alert: fired alert notification
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MetricValue   float64                `protobuf:"fixed64,3,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Severity      AlertSeverity          `protobuf:"varint,6,opt,name=severity,proto3,enum=pulse.v1.AlertSeverity" json:"severity,omitempty"`
	MetricName    string                 `protobuf:"bytes,7,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Condition     string                 `protobuf:"bytes,8,opt,name=condition,proto3" json:"condition,omitempty"`
	RuleName      string                 `protobuf:"bytes,9,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Resolved      bool                   `protobuf:"varint,10,opt,name=resolved,proto3" json:"resolved,omitempty"` // true ise: alarm sona erdi bildirimi
	Threshold     float64                `protobuf:"fixed64,11,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Alert) GetMetricValue() float64 {
	if x != nil {
		return x.MetricValue
	}
	return 0
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Alert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_INFO
}

func (x *Alert) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Alert) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *Alert) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// ListSeriesRequest: hangi seriler var?
type ListSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // bos ise tum servisler
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesRequest) Reset() {
	*x = ListSeriesRequest{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesRequest) ProtoMessage() {}

func (x *ListSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesRequest.ProtoReflect.Descriptor instead.
func (*ListSeriesRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *ListSeriesRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ListSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*SeriesRef           `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesResponse) Reset() {
	*x = ListSeriesResponse{}
	mi := &file_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesResponse) ProtoMessage() {}

func (x *ListSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesResponse.ProtoReflect.Descriptor instead.
func (*ListSeriesResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *ListSeriesResponse) GetSeries() []*SeriesRef {
	if x != nil {
		return x.Series
	}
	return nil
}

// SeriesRef: bir zaman serisinin kimligi (partition key)
type SeriesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRef) Reset() {
	*x = SeriesRef{}
	mi := &file_metrics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRef) ProtoMessage() {}

func (x *SeriesRef) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRef.ProtoReflect.Descriptor instead.
func (*SeriesRef) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{12}
}

func (x *SeriesRef) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SeriesRef) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_metrics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // bagimliliklar (ScyllaDB) erisilebilir mi?
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_metrics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type CreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleResponse) Reset() {
	*x = CreateRuleResponse{}
	mi := &file_metrics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleResponse) ProtoMessage() {}

func (x *CreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // bos ise hepsi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_metrics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{16}
}

func (x *ListRulesRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_metrics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{17}
}

func (x *ListRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_metrics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_metrics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRuleResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	StartTimeMs   int64                  `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	FiringOnly    bool                   `protobuf:"varint,5,opt,name=firing_only,json=firingOnly,proto3" json:"firing_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_metrics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{20}
}

func (x *ListAlertsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListAlertsRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *ListAlertsRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *ListAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertsRequest) GetFiringOnly() bool {
	if x != nil {
		return x.FiringOnly
	}
	return false
}

type ListAlertsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Alerts []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	// active_rule_ids: su anda tetiklenmis durumdaki kurallar
	ActiveRuleIds []string `protobuf:"bytes,2,rep,name=active_rule_ids,json=activeRuleIds,proto3" json:"active_rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_metrics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{21}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListAlertsResponse) GetActiveRuleIds() []string {
	if x != nil {
		return x.ActiveRuleIds
	}
	return nil
}

// EvaluateRulesRequest: kurallari hemen degerlendir (test ve demo icin).
type EvaluateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // bos ise tum etkin kurallar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesRequest) Reset() {
	*x = EvaluateRulesRequest{}
	mi := &file_metrics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesRequest) ProtoMessage() {}

func (x *EvaluateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRulesRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{22}
}

func (x *EvaluateRulesRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type EvaluateRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fired         []*Alert               `protobuf:"bytes,1,rep,name=fired,proto3" json:"fired,omitempty"`
	Evaluated     int32                  `protobuf:"varint,2,opt,name=evaluated,proto3" json:"evaluated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesResponse) Reset() {
	*x = EvaluateRulesResponse{}
	mi := &file_metrics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesResponse) ProtoMessage() {}

func (x *EvaluateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRulesResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{23}
}

func (x *EvaluateRulesResponse) GetFired() []*Alert {
	if x != nil {
		return x.Fired
	}
	return nil
}

func (x *EvaluateRulesResponse) GetEvaluated() int32 {
	if x != nil {
		return x.Evaluated
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\bpulse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\x0eMetricsPayload\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12*\n" +
	"\ametrics\x18\x03 \x03(\v2\x10.pulse.v1.MetricR\ametrics\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe1\x02\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.pulse.v1.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12.\n" +
	"\x04tags\x18\x04 \x03(\v2\x1a.pulse.v1.Metric.TagsEntryR\x04tags\x124\n" +
	"\x06labels\x18\x05 \x03(\v2\x1c.pulse.v1.Metric.LabelsEntryR\x06labels\x12)\n" +
	"\x10timestamp_millis\x18\x06 \x01(\x03R\x0ftimestampMillis\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x0fHistogramBucket\x12\x0e\n" +
	"\x02le\x18\x01 \x01(\x01R\x02le\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"@\n" +
	"\fSummaryValue\x12\x1a\n" +
	"\bquantile\x18\x01 \x01(\x01R\bquantile\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xf8\x02\n" +
	"\x13MetricsQueryRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12D\n" +
	"\afilters\x18\x03 \x03(\v2*.pulse.v1.MetricsQueryRequest.FiltersEntryR\afilters\x12\"\n" +
	"\rstart_time_ms\x18\x04 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x05 \x01(\x03R\tendTimeMs\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12 \n" +
	"\vaggregation\x18\a \x01(\tR\vaggregation\x12\x1f\n" +
	"\vinstance_id\x18\b \x01(\tR\n" +
	"instanceId\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x14MetricsQueryResponse\x120\n" +
	"\x06series\x18\x01 \x03(\v2\x18.pulse.v1.TimeSeriesDataR\x06series\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x03R\vqueryTimeMs\"\x9a\x02\n" +
	"\x0eTimeSeriesData\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x126\n" +
	"\x04tags\x18\x02 \x03(\v2\".pulse.v1.TimeSeriesData.TagsEntryR\x04tags\x12+\n" +
	"\x06points\x18\x03 \x03(\v2\x13.pulse.v1.DataPointR\x06points\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.pulse.v1.MetricTypeR\x04type\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\tDataPoint\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xd9\x02\n" +
	"\tAlertRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1f\n" +
	"\vwebhook_url\x18\x06 \x01(\tR\n" +
	"webhookUrl\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\"\n" +
	"\rcreated_at_ms\x18\b \x01(\x03R\vcreatedAtMs\x123\n" +
	"\bseverity\x18\t \x01(\x0e2\x17.pulse.v1.AlertSeverityR\bseverity\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\"\xee\x02\n" +
	"\x05Alert\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12!\n" +
	"\fmetric_value\x18\x03 \x01(\x01R\vmetricValue\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x123\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x17.pulse.v1.AlertSeverityR\bseverity\x12\x1f\n" +
	"\vmetric_name\x18\a \x01(\tR\n" +
	"metricName\x12\x1c\n" +
	"\tcondition\x18\b \x01(\tR\tcondition\x12\x1b\n" +
	"\trule_name\x18\t \x01(\tR\bruleName\x12\x1a\n" +
	"\bresolved\x18\n" +
	" \x01(\bR\bresolved\x12\x1c\n" +
	"\tthreshold\x18\v \x01(\x01R\tthreshold\"6\n" +
	"\x11ListSeriesRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"A\n" +
	"\x12ListSeriesResponse\x12+\n" +
	"\x06series\x18\x01 \x03(\v2\x13.pulse.v1.SeriesRefR\x06series\"O\n" +
	"\tSeriesRef\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\"\x0f\n" +
	"\rHealthRequest\"e\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"-\n" +
	"\x12CreateRuleResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"5\n" +
	"\x10ListRulesRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\">\n" +
	"\x11ListRulesResponse\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.pulse.v1.AlertRuleR\x05rules\",\n" +
	"\x11DeleteRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\".\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xb1\x01\n" +
	"\x11ListAlertsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\"\n" +
	"\rstart_time_ms\x18\x02 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x03 \x01(\x03R\tendTimeMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vfiring_only\x18\x05 \x01(\bR\n" +
	"firingOnly\"e\n" +
	"\x12ListAlertsResponse\x12'\n" +
	"\x06alerts\x18\x01 \x03(\v2\x0f.pulse.v1.AlertR\x06alerts\x12&\n" +
	"\x0factive_rule_ids\x18\x02 \x03(\tR\ractiveRuleIds\"/\n" +
	"\x14EvaluateRulesRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\\\n" +
	"\x15EvaluateRulesResponse\x12%\n" +
	"\x05fired\x18\x01 \x03(\v2\x0f.pulse.v1.AlertR\x05fired\x12\x1c\n" +
	"\tevaluated\x18\x02 \x01(\x05R\tevaluated*@\n" +
	"\n" +
	"MetricType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\r\n" +
	"\tHISTOGRAM\x10\x02\x12\v\n" +
	"\aSUMMARY\x10\x03*4\n" +
	"\rAlertSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\f\n" +
	"\bCRITICAL\x10\x022\xde\x01\n" +
	"\x0eMetricsService\x12F\n" +
	"\x05Query\x12\x1d.pulse.v1.MetricsQueryRequest\x1a\x1e.pulse.v1.MetricsQueryResponse\x12G\n" +
	"\n" +
	"ListSeries\x12\x1b.pulse.v1.ListSeriesRequest\x1a\x1c.pulse.v1.ListSeriesResponse\x12;\n" +
	"\x06Health\x12\x17.pulse.v1.HealthRequest\x1a\x18.pulse.v1.HealthResponse2\xf9\x02\n" +
	"\fAlertService\x12?\n" +
	"\n" +
	"CreateRule\x12\x13.pulse.v1.AlertRule\x1a\x1c.pulse.v1.CreateRuleResponse\x12D\n" +
	"\tListRules\x12\x1a.pulse.v1.ListRulesRequest\x1a\x1b.pulse.v1.ListRulesResponse\x12G\n" +
	"\n" +
	"DeleteRule\x12\x1b.pulse.v1.DeleteRuleRequest\x1a\x1c.pulse.v1.DeleteRuleResponse\x12G\n" +
	"\n" +
	"ListAlerts\x12\x1b.pulse.v1.ListAlertsRequest\x1a\x1c.pulse.v1.ListAlertsResponse\x12P\n" +
	"\rEvaluateRules\x12\x1e.pulse.v1.EvaluateRulesRequest\x1a\x1f.pulse.v1.EvaluateRulesResponseB,Z*github.com/nisah/pulse-metrics/pkg/pulsepbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_metrics_proto_goTypes = []any{
	(MetricType)(0),               // 0: pulse.v1.MetricType
	(AlertSeverity)(0),            // 1: pulse.v1.AlertSeverity
	(*MetricsPayload)(nil),        // 2: pulse.v1.MetricsPayload
	(*Metric)(nil),                // 3: pulse.v1.Metric
	(*HistogramBucket)(nil),       // 4: pulse.v1.HistogramBucket
	(*SummaryValue)(nil),          // 5: pulse.v1.SummaryValue
	(*MetricsQueryRequest)(nil),   // 6: pulse.v1.MetricsQueryRequest
	(*MetricsQueryResponse)(nil),  // 7: pulse.v1.MetricsQueryResponse
	(*TimeSeriesData)(nil),        // 8: pulse.v1.TimeSeriesData
	(*DataPoint)(nil),             // 9: pulse.v1.DataPoint
	(*AlertRule)(nil),             // 10: pulse.v1.AlertRule
	(*Alert)(nil),                 // 11: pulse.v1.Alert
	(*ListSeriesRequest)(nil),     // 12: pulse.v1.ListSeriesRequest
	(*ListSeriesResponse)(nil),    // 13: pulse.v1.ListSeriesResponse
	(*SeriesRef)(nil),             // 14: pulse.v1.SeriesRef
	(*HealthRequest)(nil),         // 15: pulse.v1.HealthRequest
	(*HealthResponse)(nil),        // 16: pulse.v1.HealthResponse
	(*CreateRuleResponse)(nil),    // 17: pulse.v1.CreateRuleResponse
	(*ListRulesRequest)(nil),      // 18: pulse.v1.ListRulesRequest
	(*ListRulesResponse)(nil),     // 19: pulse.v1.ListRulesResponse
	(*DeleteRuleRequest)(nil),     // 20: pulse.v1.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),    // 21: pulse.v1.DeleteRuleResponse
	(*ListAlertsRequest)(nil),     // 22: pulse.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),    // 23: pulse.v1.ListAlertsResponse
	(*EvaluateRulesRequest)(nil),  // 24: pulse.v1.EvaluateRulesRequest
	(*EvaluateRulesResponse)(nil), // 25: pulse.v1.EvaluateRulesResponse
	nil,                           // 26: pulse.v1.Metric.TagsEntry
	nil,                           // 27: pulse.v1.Metric.LabelsEntry
	nil,                           // 28: pulse.v1.MetricsQueryRequest.FiltersEntry
	nil,                           // 29: pulse.v1.TimeSeriesData.TagsEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	3,  // 0: pulse.v1.MetricsPayload.metrics:type_name -> pulse.v1.Metric
	30, // 1: pulse.v1.MetricsPayload.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: pulse.v1.Metric.type:type_name -> pulse.v1.MetricType
	26, // 3: pulse.v1.Metric.tags:type_name -> pulse.v1.Metric.TagsEntry
	27, // 4: pulse.v1.Metric.labels:type_name -> pulse.v1.Metric.LabelsEntry
	28, // 5: pulse.v1.MetricsQueryRequest.filters:type_name -> pulse.v1.MetricsQueryRequest.FiltersEntry
	8,  // 6: pulse.v1.MetricsQueryResponse.series:type_name -> pulse.v1.TimeSeriesData
	29, // 7: pulse.v1.TimeSeriesData.tags:type_name -> pulse.v1.TimeSeriesData.TagsEntry
	9,  // 8: pulse.v1.TimeSeriesData.points:type_name -> pulse.v1.DataPoint
	0,  // 9: pulse.v1.TimeSeriesData.type:type_name -> pulse.v1.MetricType
	1,  // 10: pulse.v1.AlertRule.severity:type_name -> pulse.v1.AlertSeverity
	1,  // 11: pulse.v1.Alert.severity:type_name -> pulse.v1.AlertSeverity
	14, // 12: pulse.v1.ListSeriesResponse.series:type_name -> pulse.v1.SeriesRef
	10, // 13: pulse.v1.ListRulesResponse.rules:type_name -> pulse.v1.AlertRule
	11, // 14: pulse.v1.ListAlertsResponse.alerts:type_name -> pulse.v1.Alert
	11, // 15: pulse.v1.EvaluateRulesResponse.fired:type_name -> pulse.v1.Alert
	6,  // 16: pulse.v1.MetricsService.Query:input_type -> pulse.v1.MetricsQueryRequest
	12, // 17: pulse.v1.MetricsService.ListSeries:input_type -> pulse.v1.ListSeriesRequest
	15, // 18: pulse.v1.MetricsService.Health:input_type -> pulse.v1.HealthRequest
	10, // 19: pulse.v1.AlertService.CreateRule:input_type -> pulse.v1.AlertRule
	18, // 20: pulse.v1.AlertService.ListRules:input_type -> pulse.v1.ListRulesRequest
	20, // 21: pulse.v1.AlertService.DeleteRule:input_type -> pulse.v1.DeleteRuleRequest
	22, // 22: pulse.v1.AlertService.ListAlerts:input_type -> pulse.v1.ListAlertsRequest
	24, // 23: pulse.v1.AlertService.EvaluateRules:input_type -> pulse.v1.EvaluateRulesRequest
	7,  // 24: pulse.v1.MetricsService.Query:output_type -> pulse.v1.MetricsQueryResponse
	13, // 25: pulse.v1.MetricsService.ListSeries:output_type -> pulse.v1.ListSeriesResponse
	16, // 26: pulse.v1.MetricsService.Health:output_type -> pulse.v1.HealthResponse
	17, // 27: pulse.v1.AlertService.CreateRule:output_type -> pulse.v1.CreateRuleResponse
	19, // 28: pulse.v1.AlertService.ListRules:output_type -> pulse.v1.ListRulesResponse
	21, // 29: pulse.v1.AlertService.DeleteRule:output_type -> pulse.v1.DeleteRuleResponse
	23, // 30: pulse.v1.AlertService.ListAlerts:output_type -> pulse.v1.ListAlertsResponse
	25, // 31: pulse.v1.AlertService.EvaluateRules:output_type -> pulse.v1.EvaluateRulesResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
