// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: traces.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanKind int32

const (
	SpanKind_SPAN_KIND_UNSPECIFIED SpanKind = 0
	SpanKind_SPAN_KIND_INTERNAL    SpanKind = 1
	SpanKind_SPAN_KIND_SERVER      SpanKind = 2
	SpanKind_SPAN_KIND_CLIENT      SpanKind = 3
	SpanKind_SPAN_KIND_PRODUCER    SpanKind = 4
	SpanKind_SPAN_KIND_CONSUMER    SpanKind = 5
)

// Enum value maps for SpanKind.
var (
	SpanKind_name = map[int32]string{
		0: "SPAN_KIND_UNSPECIFIED",
		1: "SPAN_KIND_INTERNAL",
		2: "SPAN_KIND_SERVER",
		3: "SPAN_KIND_CLIENT",
		4: "SPAN_KIND_PRODUCER",
		5: "SPAN_KIND_CONSUMER",
	}
	SpanKind_value = map[string]int32{
		"SPAN_KIND_UNSPECIFIED": 0,
		"SPAN_KIND_INTERNAL":    1,
		"SPAN_KIND_SERVER":      2,
		"SPAN_KIND_CLIENT":      3,
		"SPAN_KIND_PRODUCER":    4,
		"SPAN_KIND_CONSUMER":    5,
	}
)

func (x SpanKind) Enum() *SpanKind {
	p := new(SpanKind)
	*p = x
	return p
}

func (x SpanKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanKind) Descriptor() protoreflect.EnumDescriptor {
	return file_traces_proto_enumTypes[0].Descriptor()
}

func (SpanKind) Type() protoreflect.EnumType {
	return &file_traces_proto_enumTypes[0]
}

func (x SpanKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanKind.Descriptor instead.
func (SpanKind) EnumDescriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSET StatusCode = 0
	StatusCode_STATUS_CODE_OK    StatusCode = 1
	StatusCode_STATUS_CODE_ERROR StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSET",
		1: "STATUS_CODE_OK",
		2: "STATUS_CODE_ERROR",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSET": 0,
		"STATUS_CODE_OK":    1,
		"STATUS_CODE_ERROR": 2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_traces_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_traces_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{1}
}

// TracesPayload: batch of spans from agent
type TracesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Spans         []*Span                `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracesPayload) Reset() {
	*x = TracesPayload{}
	mi := &file_traces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracesPayload) ProtoMessage() {}

func (x *TracesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracesPayload.ProtoReflect.Descriptor instead.
func (*TracesPayload) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{0}
}

func (x *TracesPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TracesPayload) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TracesPayload) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *TracesPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Span: single distributed trace span (OpenTelemetry compatible)
type Span struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId          string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId    string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	OperationName   string                 `protobuf:"bytes,4,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ServiceName     string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	StartTimeMicros int64                  `protobuf:"varint,6,opt,name=start_time_micros,json=startTimeMicros,proto3" json:"start_time_micros,omitempty"`
	EndTimeMicros   int64                  `protobuf:"varint,7,opt,name=end_time_micros,json=endTimeMicros,proto3" json:"end_time_micros,omitempty"`
	Kind            SpanKind               `protobuf:"varint,8,opt,name=kind,proto3,enum=pulse.v1.SpanKind" json:"kind,omitempty"`
	Status          *SpanStatus            `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Attributes      map[string]string      `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // tags, labels
	Events          []*Event               `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	Links           []*Link                `protobuf:"bytes,12,rep,name=links,proto3" json:"links,omitempty"`
	// OpenTelemetry trace state (for propagation)
	TraceState    string `protobuf:"bytes,13,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_traces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetStartTimeMicros() int64 {
	if x != nil {
		return x.StartTimeMicros
	}
	return 0
}

func (x *Span) GetEndTimeMicros() int64 {
	if x != nil {
		return x.EndTimeMicros
	}
	return 0
}

func (x *Span) GetKind() SpanKind {
	if x != nil {
		return x.Kind
	}
	return SpanKind_SPAN_KIND_UNSPECIFIED
}

func (x *Span) GetStatus() *SpanStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Span) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Span) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Span) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

type SpanStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=pulse.v1.StatusCode" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanStatus) Reset() {
	*x = SpanStatus{}
	mi := &file_traces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanStatus) ProtoMessage() {}

func (x *SpanStatus) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanStatus.ProtoReflect.Descriptor instead.
func (*SpanStatus) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{2}
}

func (x *SpanStatus) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_UNSET
}

func (x *SpanStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Event: span event (e.g., exception, log)
type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimestampMicros int64                  `protobuf:"varint,2,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"`
	Attributes      map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_traces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *Event) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Link: reference to another span
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_traces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{4}
}

func (x *Link) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Link) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Link) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// TraceQuery: query for historical traces
type TraceQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartTimeMs   int64                  `protobuf:"varint,4,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,5,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	MinDurationMs int32                  `protobuf:"varint,6,opt,name=min_duration_ms,json=minDurationMs,proto3" json:"min_duration_ms,omitempty"` // filter by min latency
	MaxDurationMs int32                  `protobuf:"varint,7,opt,name=max_duration_ms,json=maxDurationMs,proto3" json:"max_duration_ms,omitempty"` // filter by max latency
	ErrorsOnly    bool                   `protobuf:"varint,8,opt,name=errors_only,json=errorsOnly,proto3" json:"errors_only,omitempty"`
	Limit         int32                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceQueryRequest) Reset() {
	*x = TraceQueryRequest{}
	mi := &file_traces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceQueryRequest) ProtoMessage() {}

func (x *TraceQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceQueryRequest.ProtoReflect.Descriptor instead.
func (*TraceQueryRequest) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{5}
}

func (x *TraceQueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TraceQueryRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *TraceQueryRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *TraceQueryRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *TraceQueryRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *TraceQueryRequest) GetMinDurationMs() int32 {
	if x != nil {
		return x.MinDurationMs
	}
	return 0
}

func (x *TraceQueryRequest) GetMaxDurationMs() int32 {
	if x != nil {
		return x.MaxDurationMs
	}
	return 0
}

func (x *TraceQueryRequest) GetErrorsOnly() bool {
	if x != nil {
		return x.ErrorsOnly
	}
	return false
}

func (x *TraceQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// TraceQueryResponse: matching traces
type TraceQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	QueryTimeMs   int64                  `protobuf:"varint,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	TotalMatches  int64                  `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceQueryResponse) Reset() {
	*x = TraceQueryResponse{}
	mi := &file_traces_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceQueryResponse) ProtoMessage() {}

func (x *TraceQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceQueryResponse.ProtoReflect.Descriptor instead.
func (*TraceQueryResponse) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{6}
}

func (x *TraceQueryResponse) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *TraceQueryResponse) GetQueryTimeMs() int64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

func (x *TraceQueryResponse) GetTotalMatches() int64 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

// Trace: reconstructed complete trace (all spans)
type Trace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Spans           []*Span                `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	StartTimeMicros int64                  `protobuf:"varint,3,opt,name=start_time_micros,json=startTimeMicros,proto3" json:"start_time_micros,omitempty"`
	DurationMicros  int64                  `protobuf:"varint,4,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	SpanCount       int32                  `protobuf:"varint,5,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"`
	HasError        bool                   `protobuf:"varint,6,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_traces_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{7}
}

func (x *Trace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Trace) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *Trace) GetStartTimeMicros() int64 {
	if x != nil {
		return x.StartTimeMicros
	}
	return 0
}

func (x *Trace) GetDurationMicros() int64 {
	if x != nil {
		return x.DurationMicros
	}
	return 0
}

func (x *Trace) GetSpanCount() int32 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

func (x *Trace) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

// ServiceDependency: auto-discovered service relationships
type ServiceDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerService string                 `protobuf:"bytes,1,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"`
	CalleeService string                 `protobuf:"bytes,2,opt,name=callee_service,json=calleeService,proto3" json:"callee_service,omitempty"`
	CallCount     int64                  `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	P50LatencyMs  int64                  `protobuf:"varint,5,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs  int64                  `protobuf:"varint,6,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs  int64                  `protobuf:"varint,7,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDependency) Reset() {
	*x = ServiceDependency{}
	mi := &file_traces_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDependency) ProtoMessage() {}

func (x *ServiceDependency) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDependency.ProtoReflect.Descriptor instead.
func (*ServiceDependency) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceDependency) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

func (x *ServiceDependency) GetCalleeService() string {
	if x != nil {
		return x.CalleeService
	}
	return ""
}

func (x *ServiceDependency) GetCallCount() int64 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *ServiceDependency) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ServiceDependency) GetP50LatencyMs() int64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *ServiceDependency) GetP95LatencyMs() int64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *ServiceDependency) GetP99LatencyMs() int64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

// ServiceTopology: complete dependency graph
type ServiceTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ServiceNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*ServiceDependency   `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTopology) Reset() {
	*x = ServiceTopology{}
	mi := &file_traces_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTopology) ProtoMessage() {}

func (x *ServiceTopology) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTopology.ProtoReflect.Descriptor instead.
func (*ServiceTopology) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceTopology) GetNodes() []*ServiceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceTopology) GetEdges() []*ServiceDependency {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ServiceTopology) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// ServiceNode: node in dependency graph
type ServiceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceCount int32                  `protobuf:"varint,2,opt,name=instance_count,json=instanceCount,proto3" json:"instance_count,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNode) Reset() {
	*x = ServiceNode{}
	mi := &file_traces_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNode) ProtoMessage() {}

func (x *ServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNode.ProtoReflect.Descriptor instead.
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceNode) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceNode) GetInstanceCount() int32 {
	if x != nil {
		return x.InstanceCount
	}
	return 0
}

func (x *ServiceNode) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ServiceNode) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *ServiceNode) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetTraceRequest: tek bir trace'i id ile getir
type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_traces_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{11}
}

func (x *GetTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// TopologyRequest: servis bagimlilik grafigi
type TopologyRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StartTimeMs int64                  `protobuf:"varint,1,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs   int64                  `protobuf:"varint,2,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	// sample_limit: topoloji, son N trace ornegi uzerinden hesaplanir.
	// Butun trace'leri okumak pahali oldugu icin sinirli bir ornek kullanilir.
	SampleLimit   int32 `protobuf:"varint,3,opt,name=sample_limit,json=sampleLimit,proto3" json:"sample_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_traces_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{12}
}

func (x *TopologyRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *TopologyRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *TopologyRequest) GetSampleLimit() int32 {
	if x != nil {
		return x.SampleLimit
	}
	return 0
}

// ListOperationsRequest: bir servisin bilinen operasyonlari
type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_traces_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{13}
}

func (x *ListOperationsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []string               `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	Services      []string               `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_traces_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traces_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_traces_proto_rawDescGZIP(), []int{14}
}

func (x *ListOperationsResponse) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_traces_proto protoreflect.FileDescriptor

const file_traces_proto_rawDesc = "" +
	"\n" +
	"\ftraces.proto\x12\bpulse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\rTracesPayload\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x05spans\x18\x03 \x03(\v2\x0e.pulse.v1.SpanR\x05spans\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc3\x04\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12%\n" +
	"\x0eoperation_name\x18\x04 \x01(\tR\roperationName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12*\n" +
	"\x11start_time_micros\x18\x06 \x01(\x03R\x0fstartTimeMicros\x12&\n" +
	"\x0fend_time_micros\x18\a \x01(\x03R\rendTimeMicros\x12&\n" +
	"\x04kind\x18\b \x01(\x0e2\x12.pulse.v1.SpanKindR\x04kind\x12,\n" +
	"\x06status\x18\t \x01(\v2\x14.pulse.v1.SpanStatusR\x06status\x12>\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2\x1e.pulse.v1.Span.AttributesEntryR\n" +
	"attributes\x12'\n" +
	"\x06events\x18\v \x03(\v2\x0f.pulse.v1.EventR\x06events\x12$\n" +
	"\x05links\x18\f \x03(\v2\x0e.pulse.v1.LinkR\x05links\x12\x1f\n" +
	"\vtrace_state\x18\r \x01(\tR\n" +
	"traceState\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\n" +
	"SpanStatus\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.pulse.v1.StatusCodeR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xc6\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10timestamp_micros\x18\x02 \x01(\x03R\x0ftimestampMicros\x12?\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1f.pulse.v1.Event.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x04Link\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12>\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1e.pulse.v1.Link.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x03\n" +
	"\x11TraceQueryRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12B\n" +
	"\afilters\x18\x03 \x03(\v2(.pulse.v1.TraceQueryRequest.FiltersEntryR\afilters\x12\"\n" +
	"\rstart_time_ms\x18\x04 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x05 \x01(\x03R\tendTimeMs\x12&\n" +
	"\x0fmin_duration_ms\x18\x06 \x01(\x05R\rminDurationMs\x12&\n" +
	"\x0fmax_duration_ms\x18\a \x01(\x05R\rmaxDurationMs\x12\x1f\n" +
	"\verrors_only\x18\b \x01(\bR\n" +
	"errorsOnly\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x12TraceQueryResponse\x12'\n" +
	"\x06traces\x18\x01 \x03(\v2\x0f.pulse.v1.TraceR\x06traces\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x03R\vqueryTimeMs\x12#\n" +
	"\rtotal_matches\x18\x03 \x01(\x03R\ftotalMatches\"\xd9\x01\n" +
	"\x05Trace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12$\n" +
	"\x05spans\x18\x02 \x03(\v2\x0e.pulse.v1.SpanR\x05spans\x12*\n" +
	"\x11start_time_micros\x18\x03 \x01(\x03R\x0fstartTimeMicros\x12'\n" +
	"\x0fduration_micros\x18\x04 \x01(\x03R\x0edurationMicros\x12\x1d\n" +
	"\n" +
	"span_count\x18\x05 \x01(\x05R\tspanCount\x12\x1b\n" +
	"\thas_error\x18\x06 \x01(\bR\bhasError\"\x91\x02\n" +
	"\x11ServiceDependency\x12%\n" +
	"\x0ecaller_service\x18\x01 \x01(\tR\rcallerService\x12%\n" +
	"\x0ecallee_service\x18\x02 \x01(\tR\rcalleeService\x12\x1d\n" +
	"\n" +
	"call_count\x18\x03 \x01(\x03R\tcallCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12$\n" +
	"\x0ep50_latency_ms\x18\x05 \x01(\x03R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x06 \x01(\x03R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\a \x01(\x03R\fp99LatencyMs\"\x94\x01\n" +
	"\x0fServiceTopology\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.pulse.v1.ServiceNodeR\x05nodes\x121\n" +
	"\x05edges\x18\x02 \x03(\v2\x1b.pulse.v1.ServiceDependencyR\x05edges\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\x9a\x02\n" +
	"\vServiceNode\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0einstance_count\x18\x02 \x01(\x05R\rinstanceCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x01R\terrorRate\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.pulse.v1.ServiceNode.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x0fGetTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"x\n" +
	"\x0fTopologyRequest\x12\"\n" +
	"\rstart_time_ms\x18\x01 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x02 \x01(\x03R\tendTimeMs\x12!\n" +
	"\fsample_limit\x18\x03 \x01(\x05R\vsampleLimit\":\n" +
	"\x15ListOperationsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"T\n" +
	"\x16ListOperationsResponse\x12\x1e\n" +
	"\n" +
	"operations\x18\x01 \x03(\tR\n" +
	"operations\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices*\x99\x01\n" +
	"\bSpanKind\x12\x19\n" +
	"\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SPAN_KIND_INTERNAL\x10\x01\x12\x14\n" +
	"\x10SPAN_KIND_SERVER\x10\x02\x12\x14\n" +
	"\x10SPAN_KIND_CLIENT\x10\x03\x12\x16\n" +
	"\x12SPAN_KIND_PRODUCER\x10\x04\x12\x16\n" +
	"\x12SPAN_KIND_CONSUMER\x10\x05*N\n" +
	"\n" +
	"StatusCode\x12\x15\n" +
	"\x11STATUS_CODE_UNSET\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CODE_OK\x10\x01\x12\x15\n" +
	"\x11STATUS_CODE_ERROR\x10\x022\xaa\x02\n" +
	"\fTraceService\x12H\n" +
	"\vQueryTraces\x12\x1b.pulse.v1.TraceQueryRequest\x1a\x1c.pulse.v1.TraceQueryResponse\x126\n" +
	"\bGetTrace\x12\x19.pulse.v1.GetTraceRequest\x1a\x0f.pulse.v1.Trace\x12C\n" +
	"\vGetTopology\x12\x19.pulse.v1.TopologyRequest\x1a\x19.pulse.v1.ServiceTopology\x12S\n" +
	"\x0eListOperations\x12\x1f.pulse.v1.ListOperationsRequest\x1a .pulse.v1.ListOperationsResponseB,Z*github.com/nisah/pulse-metrics/pkg/pulsepbb\x06proto3"

var (
	file_traces_proto_rawDescOnce sync.Once
	file_traces_proto_rawDescData []byte
)

func file_traces_proto_rawDescGZIP() []byte {
	file_traces_proto_rawDescOnce.Do(func() {
		file_traces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traces_proto_rawDesc), len(file_traces_proto_rawDesc)))
	})
	return file_traces_proto_rawDescData
}

var file_traces_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_traces_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_traces_proto_goTypes = []any{
	(SpanKind)(0),                  // 0: pulse.v1.SpanKind
	(StatusCode)(0),                // 1: pulse.v1.StatusCode
	(*TracesPayload)(nil),          // 2: pulse.v1.TracesPayload
	(*Span)(nil),                   // 3: pulse.v1.Span
	(*SpanStatus)(nil),             // 4: pulse.v1.SpanStatus
	(*Event)(nil),                  // 5: pulse.v1.Event
	(*Link)(nil),                   // 6: pulse.v1.Link
	(*TraceQueryRequest)(nil),      // 7: pulse.v1.TraceQueryRequest
	(*TraceQueryResponse)(nil),     // 8: pulse.v1.TraceQueryResponse
	(*Trace)(nil),                  // 9: pulse.v1.Trace
	(*ServiceDependency)(nil),      // 10: pulse.v1.ServiceDependency
	(*ServiceTopology)(nil),        // 11: pulse.v1.ServiceTopology
	(*ServiceNode)(nil),            // 12: pulse.v1.ServiceNode
	(*GetTraceRequest)(nil),        // 13: pulse.v1.GetTraceRequest
	(*TopologyRequest)(nil),        // 14: pulse.v1.TopologyRequest
	(*ListOperationsRequest)(nil),  // 15: pulse.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil), // 16: pulse.v1.ListOperationsResponse
	nil,                            // 17: pulse.v1.Span.AttributesEntry
	nil,                            // 18: pulse.v1.Event.AttributesEntry
	nil,                            // 19: pulse.v1.Link.AttributesEntry
	nil,                            // 20: pulse.v1.TraceQueryRequest.FiltersEntry
	nil,                            // 21: pulse.v1.ServiceNode.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
}
var file_traces_proto_depIdxs = []int32{
	3,  // 0: pulse.v1.TracesPayload.spans:type_name -> pulse.v1.Span
	22, // 1: pulse.v1.TracesPayload.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: pulse.v1.Span.kind:type_name -> pulse.v1.SpanKind
	4,  // 3: pulse.v1.Span.status:type_name -> pulse.v1.SpanStatus
	17, // 4: pulse.v1.Span.attributes:type_name -> pulse.v1.Span.AttributesEntry
	5,  // 5: pulse.v1.Span.events:type_name -> pulse.v1.Event
	6,  // 6: pulse.v1.Span.links:type_name -> pulse.v1.Link
	1,  // 7: pulse.v1.SpanStatus.code:type_name -> pulse.v1.StatusCode
	18, // 8: pulse.v1.Event.attributes:type_name -> pulse.v1.Event.AttributesEntry
	19, // 9: pulse.v1.Link.attributes:type_name -> pulse.v1.Link.AttributesEntry
	20, // 10: pulse.v1.TraceQueryRequest.filters:type_name -> pulse.v1.TraceQueryRequest.FiltersEntry
	9,  // 11: pulse.v1.TraceQueryResponse.traces:type_name -> pulse.v1.Trace
	3,  // 12: pulse.v1.Trace.spans:type_name -> pulse.v1.Span
	12, // 13: pulse.v1.ServiceTopology.nodes:type_name -> pulse.v1.ServiceNode
	10, // 14: pulse.v1.ServiceTopology.edges:type_name -> pulse.v1.ServiceDependency
	21, // 15: pulse.v1.ServiceNode.metadata:type_name -> pulse.v1.ServiceNode.MetadataEntry
	7,  // 16: pulse.v1.TraceService.QueryTraces:input_type -> pulse.v1.TraceQueryRequest
	13, // 17: pulse.v1.TraceService.GetTrace:input_type -> pulse.v1.GetTraceRequest
	14, // 18: pulse.v1.TraceService.GetTopology:input_type -> pulse.v1.TopologyRequest
	15, // 19: pulse.v1.TraceService.ListOperations:input_type -> pulse.v1.ListOperationsRequest
	8,  // 20: pulse.v1.TraceService.QueryTraces:output_type -> pulse.v1.TraceQueryResponse
	9,  // 21: pulse.v1.TraceService.GetTrace:output_type -> pulse.v1.Trace
	11, // 22: pulse.v1.TraceService.GetTopology:output_type -> pulse.v1.ServiceTopology
	16, // 23: pulse.v1.TraceService.ListOperations:output_type -> pulse.v1.ListOperationsResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_traces_proto_init() }
func file_traces_proto_init() {
	if File_traces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traces_proto_rawDesc), len(file_traces_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_traces_proto_goTypes,
		DependencyIndexes: file_traces_proto_depIdxs,
		EnumInfos:         file_traces_proto_enumTypes,
		MessageInfos:      file_traces_proto_msgTypes,
	}.Build()
	File_traces_proto = out.File
	file_traces_proto_goTypes = nil
	file_traces_proto_depIdxs = nil
}
